# Generated by Django 4.0.3 on 2024-01-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0002_post_date_created_post_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(default='department', max_length=250),
        ),
    ]
